URL matching abstraction
balazsgerlei/SecureWebView pull request #19
Opened 2024-07-12 12:49 UTC by drathar

This is my proposed alternative solution to #18.

I've created the `UrlMatcher` interface and various implementations for every possible value of the `MatchVariant` enumeration.
I've also created the `DeniedUrlList` and `AllowedUrlList` classes both implementing `UrlMatcher` to be used as compound matchers instead of using a `List<DisallowedUrl>` and `List<String>` respectively. This gives a nice API and more freedom over the allow-list as not only host matching can be checked using the `UrlMatcher` interface.

If you don't like this kind of abstraction feel free to close my PR and the corresponding issue, otherwise any observations, suggestions, ideas, etc. are more than welcome. 👍🏻

2024-09-03 10:28 UTC, balazsgerlei requested changes
Thank you very much for your contribution, I really like the concept and the fact that it provides more flexibility for defining allowed and disallowed URIs. It's a huge bonus that you made it possible to unit test it, it's been on my TODO list since I started working on this library and this is a good basis to build on!

I added my remarks and suggestions, please check them and implement them if you agree, while I'm always open for discussion! Thanks for your patience while waiting on my review I was struggling to fit it in.

2024-09-11 07:13 UTC, drathar commented on library/src/main/java/dev/gerlot/securewebview/SecureWebView.java
> +    private DeniedUrlList deniedUrlList = null;
I have no hard argument, it just sounds more appropriate to me and I usually see "denied" as the opposite of "allowed".
I'll rename this to `disallowedUrlList` if that is more familiar with you.

2024-09-11 07:29 UTC, drathar commented on library/src/main/java/dev/gerlot/securewebview/url/UriMatcher.java
> + * for authorization.
Shoot. 😅 Busted. 😄 Removed this part of the comment. Thanks for the notice. 👍🏻

2024-09-17 18:59 UTC, balazsgerlei commented on library/src/main/java/dev/gerlot/securewebview/SecureWebView.java
> +    private DeniedUrlList deniedUrlList = null;
Please do use "disallowed" instead of "denied", thanks!

2024-10-02 15:19 UTC, drathar commented on library/src/main/java/dev/gerlot/securewebview/url/AllowedUrlList.java
> +    }
Fixed. Did the same for the `DisallowedUriMatcher`.

2024-10-02 15:32 UTC, drathar commented on library/src/test/java/dev/gerlot/securewebview/url/DeniedUrlListTest.java
> +        DeniedUrlList denyList = new DeniedUrlList(List.of(uri -> Objects.equals(uri.getAuthority(), "google.com") || Objects.equals(uri.getAuthority(), "bing.com")));
Fixed in test.

I think it's arguable which one to encourage and if it's worth at all to encourage one over the other. I'd lean towards your preference, although I believe this is something we could easily iterate on and not necessary to decide now.

2024-10-02 19:21 UTC, drathar commented on library/src/main/java/dev/gerlot/securewebview/SecureWebView.java
> +        return deniedUrlList.matches(uri);
You're right. I must have been slightly confused when implemented these changes.

Although, I remember that I wanted to distinguish allow and disallow lists and I might have overdone it by unnecessarily inverting the logic in the `DisallowedUriList` class.

Anyway, I simply removed both `AllowedUriList` and `DisallowedUriList` in favour of using `UriList` for both intention.
I also fixed the return statement.

2024-10-03 05:52 UTC, balazsgerlei commented on library/src/test/java/dev/gerlot/securewebview/url/DeniedUrlListTest.java
> +        DeniedUrlList denyList = new DeniedUrlList(List.of(uri -> Objects.equals(uri.getAuthority(), "google.com") || Objects.equals(uri.getAuthority(), "bing.com")));
Yeah, you are right, I'll also think about it in the mean time, thanks for the changes!

2024-10-03 05:56 UTC, balazsgerlei approved these changes

2024-10-03 06:02 UTC, merged